### ISSUE TITLE
Rename Teleports?

### ISSUE THREAD

**Issue by SandroVA** [ejaz-karim/reword-manager#1]
Would it be possible to rename teleport locations using this? I'd like to rename the teleports of the ring of shadows to their respective bosses:
`Ghorrock Dungeon, Duke`
`The Scar, Leviathan`
`Lassar Undercity, The Whisperer`
`The Stranglewood, Vardorvis`

Sadly putting these under "Chat List" doesn't work.

**Comment by ejaz-karim** [comment]
Thanks for the suggestion. I am working on implementing rewording for Options for this to work.

**Comment by ejaz-karim** [comment]
I've added the functionality to reword options, which allows teleports to be reworded. This will be included in the next version update.
