### ISSUE TITLE
CC/FC [Name] tag

### ISSUE THREAD

**Issue by Noaburr** [ejaz-karim/reword-manager#3]
Is it possible to reword this? I've been searching for a plugin that would do this for months, and this seems to be the most likely one that could do it. If not possible please consider adding this functionality as it'd be massively appreciated! 

Example:
[Clan Name] Username: Chat message
[Reworded] Username: Chat message

**Comment by ejaz-karim** [comment]
With the 1.3.0 update, this is now possible.
https://github.com/runelite/plugin-hub/pull/5534
