### ISSUE TITLE
Reword Manager Broken?

### ISSUE THREAD

**Issue by SandroVA** [ejaz-karim/reword-manager#5]
Items, NPCs and Options all aren't working anymore. Not sure about the rest.

**Comment by ejaz-karim** [comment]
Its working for me. Can you try resetting the plugin and see if that fixes your issue.

**Comment by SandroVA** [comment]
I uninstalled and reinstalled and its still not working. I even removed all my options and tried just renaming one item or npc but that also did not work.

Heres my runelite profile if that helps:
[NotSoCasual.json](https://github.com/ejaz-karim/reword-manager/files/14544255/NotSoCasual.json)

(You'll need to rename NotSoCasual.json to NotSoCasual.properties to be able to import it.

**Comment by ejaz-karim** [comment]
I used your runelite profile and fixed it by resetting the plugin and pasting in your list but using only one new line, and not two.
![image](https://github.com/ejaz-karim/reword-manager/assets/78738965/5c355796-c64c-471a-83d4-0d552fc3010c)
![image](https://github.com/ejaz-karim/reword-manager/assets/78738965/e53eb632-4972-44eb-a27c-1ad88ad24904)
