### ISSUE TITLE
renaming breaks Teleport submenus functionality

### ISSUE THREAD

**Issue by mejrs** [ejaz-karim/reword-manager#6]
I have the following reword:
```
Construct. cape(t),Construction cape(t)
```

This however breaks the Teleport submenus function released today ( https://runelite.net/blog/show/2024-04-17-1.10.27-Release/ ). Leftclicking the cape does nothing if one of the new options is set to leftclick.

**Comment by ejaz-karim** [comment]
Is there a way for me to test this as I don't own a Max/Achievement/Construction cape?

**Comment by ejaz-karim** [comment]
>Also it would be great if the Option List worked with submenus.
thanks for the suggestion. do you know any items that have submenus that aren't those three capes?

**Comment by mejrs** [comment]
It appears to work now.
