### ISSUE TITLE
Rewording chat list for words followed by punctuation & multiple word phrases

### ISSUE THREAD

**Issue by ixiolirionx** [ejaz-karim/reword-manager#8]
Is there a way to modify words that are followed by a . or ! or similar?
Also is it possible to modify multiple word phrases in this section?

For example, modifying "Nothing interesting happens."
"Nothing,test" gives "[Modified] test interesting happens." <- changes as expected
"Nothing interesting,test" gives "[Modified] Nothing interesting happens." <- nothing has changed here but it still shows the Modified message showing that it is recognising that the phrase it should be changing is there but it isn't doing anything
"happens,test" and "happens.,test" both give "Nothing interesting happens." <- not recognising that there's a word to change at all.

If there's already a way of doing this it might be a good idea to mention how to do it somewhere. :)

**Comment by ejaz-karim** [comment]
1.3.1 is now live which should allow punctuation. The case where there is two words being reworded into one word is technically possible
e.g.
>"Nothing interesting,test"

However, it always seems to break other parts of the plugin and basic test cases will fail. So, as a compromise for now you can only just do 1:1 rewording. If you can come up with a solution, feel free to send a pull request.
