### ISSUE TITLE
[Modified] remover/variable

### ISSUE THREAD

**Issue by Erutpur** [ejaz-karim/reword-manager#9]
Hello dear developer,
Thank you for providing us scapers this cool feature to shorten tedious names.
Is there a possibility to remove the [Modified] display ingame? Or change it to [M]?
![image](https://github.com/ejaz-karim/reword-manager/assets/91503098/fc1be88c-a3da-45b7-bfc5-57ab00ce06fd)

Cheers

**Comment by ejaz-karim** [comment]
https://github.com/ejaz-karim/reword-manager/issues/7
If you can convince Nightfirecat, the runelite plugin moderator, then sure. Otherwise, I won't be able to remove the tag.
